<style>
	@import url("reset.css");

body {
    font-family: Verdana, Arial, Helvetica, sans-serif;
    font-size: 13px;
    color:#333
			top: 0px;
		margin:0 auto;
		position:relative; /* puts container in front of distance */
		text-align:left;
		height:700px;
		width:1000px;
		clear:left;
		background-color:#FFFFFF;
}


p {
    padding: 10px;
}

#wrapper {
    margin: 0 auto;
    width: 1000px;
}

#headerwrap {
    margin: 0 auto;
    width: 1000px;
}

#header {
    height: 100px;
    background: #191970;
    border-radius: 10px;
    border: 1px solid #191970;
    margin: 5px;
}

#contentwrap {
    float: right;
    margin: 0 auto;
    width: 564px;
}

#content {
    background: #4682b4;
    border-radius: 10px;
    border: 1px solid #4682b4;
    margin: 5px;
	height: 500px;
	width: 807
}

#leftcolumnwrap {
    float: left;
    margin: 0 auto;
    width: 180px;
	
}

#leftcolumn {
    background: #191970;
    border-radius: 10px;
    border: 1px solid #191970;
    margin: 5px;
	height: 500px
}

#footerwrap {
    width: 1000px;
    float: center;
    margin: 0 auto;
	clear: both;
}

#footer {
    height: 40px;
    background: #191970;
    border-radius: 10px;
    border: 1px solid #191970;
    margin: 5px;
}
    
    /* Styles für das Menü */	
	/***********************/

#menu8 {
		width: 200px;
		margin-top: 10px;
	}	
	
#menu8 li a {
		text-decoration: none;
		height: 32px;
	  	voice-family: "\"}\""; 
	  	voice-family: inherit;
	  	height: 24px;
	}
		
#menu8 li a:link, #menu8 li a:visited {
		color: #777;
		display: block;
		background: url(images/menu8.gif);
		padding: 8px 0 0 20px;
	}
		
#menu8 li a:hover {
		color: #257EB7;
		background: url(images/menu8.gif) 0 -32px;
		padding: 8px 0 0 25px;
	}
		
#menu8 li a:active {
		color: #fff;
		background: url(images/menu8.gif) 0 -64px;
		padding: 8px 0 0 25px;
	}
	
	#menu8 ul {
		list-style: none;
		margin: 0;
		padding: 0;
	}
}

</style>

<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>Dictro</title>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
</head>
<body>
 
 <div id="wrapper">
        <div id="headerwrap">
		    <div id="header">
		        <?php echo $this->action('index', 'header')?>
		    </div>
	    </div>
	    
	    <div id="leftcolumnwrap"  class="menue" style="float:left">
		    <div id="leftcolumn">
			    <div id="menu8">
			        <?php echo $this->action('index', 'menue'); ?>
			    </div>
		    </div>
	    </div>
		
		<div id="contentwrap" class="content" style="float:right">
		    <div id="content">
		         <?php echo $this->layout()->content; ?>
			</div>
        </div>
        <div id="footerwrap">
	        <div id="footer">
	            <?php echo $this->action('index', 'footer'); ?>
	        </div>
        </div>
		
 </div>
 
</body>
</html>