<style>
	
	body {
	    font-family: Verdana, Arial, Helvetica, sans-serif;
	    font-size: 13px;
	    color:#333;
		top: 0px;
		margin:0 auto;
		position:relative; /* puts container in front of distance */
		text-align:left;
		height:700px;
		width:1000px;
		clear:left;
		background-color:#b0c4de;
	}
	
	#wrapper {
	    margin: 0 auto;
	    width: 1000px;
	}
	
	#headerwrap {
	    margin: 0 auto;
	    width: 1000px;
	}
	
	#header {
	    height: 100px;
	    background: #191970;
	    border-radius: 10px;
	    border: 1px solid #191970;
	    margin: 5px;
	}
	
	#contentwrap {
	    float: right;
	    margin: 0 auto;
	    width: 564px;
	}
	
	#content {
	    background: none repeat scroll 0 0 #4682B4;
	    border: 1px solid #4682B4;
	    border-radius: 10px 10px 10px 10px;
	    margin: 6px;
	    min-height: 461px;
	    padding: 20px;
	    width: 768px;
}
	
	#leftcolumnwrap {
	    float: left;
	    margin: 0 auto;
	    width: 180px;
		
	}
	
	#leftcolumn {
	    background: #191970;
	    border-radius: 10px;
	    border: 1px solid #191970;
	    margin: 5px;
		height: 500px
	
	}
	
	#footerwrap {
	    width: 820px;
	    margin: 0 auto;
		clear: both;
		float:right;
	}
	
	#footer {
	    height: 40px;
	    background: #191970;
	    border-radius: 10px;
	    border: 1px solid #191970;
	    margin: 5px;
	}
	
	
	</style>
	



<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>Dictro</title>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
</head>
<body>
 
 <div id="wrapper">
        <div id="headerwrap">
		    <div id="header">
		        <?php echo $this->action('index', 'header')?>
		    </div>
	    </div>
	    
	    <div id="leftcolumnwrap"  class="menue" style="float:left">
		    <div id="leftcolumn">
				<div id="menu8">
			        <?php echo $this->action('index', 'menue'); ?>
				</div>
		    </div>
	    </div>
		
		<div id="contentwrap" class="content" style="float:right">
		    <div id="content">
		         <?php echo $this->layout()->content; ?> 
			</div>
        </div>
        
        <div id="footerwrap">
	        <div id="footer">
	            <?php echo $this->action('index', 'footer'); ?>
	        </div>
        </div>
		
 </div>
 
</body>
</html>