
<div class="content">
			
			<div id="imprint_eng">
			
			<h1>Imprint</h1>
		
			<br>
			
				  The author assumes no responsibility for the topicality, correctness, completeness or quality of the information. 
						  Liability claims against the author, which refer to material or immaterial damage, caused by the use or disuse of the 
						  information or the use of incorrect or incomplete information are excluded, provided that there is no intentional or grossly 
						  negligent by the author.<br />
						  All offers are non-binding. The author expressly reserves the right, parts of the pages or the entire offer without prior notice 
						  to change, amend, delete or adjust the publication temporarily or permanently.<br /><br />
						  <b>1. References and links</b><br />
						  With direct or indirect references to other websites ("hyperlinks") which lie outside the responsibility of the author, liability 
						  would only come into effect if, in which the author has knowledge of the contents and would be technically possible and reasonable 
						  to prevent the use of illegal content<br />
						  The author hereby expressly declares that at the time of linking, ther is no illegal content on the linked pages. On the current and future 
						  design, the autor has no influence of contents or authorship of the linked sides. He therefore expressly distances himself 
						  from all contents of all linked/connected pages which were changed after setting the link. This statement applies to all set links and references as 
						  well as for external entries in guest books, discussion forums, link directories, mailing lists 
						  and all other forms of databases to which external access is possible. For illegal, incorrect or incomplete contents and especially for 
						  damages resulting from the use or disuse of such information, only the provider of the linked site is responsible, not the one who set the links.
						  <br /><br />
						  <b>2. Copyright and trademark law</b><br />
						  The author endeavors to observe the copyrights of the used images, graphics, sound files, video sequences and texts, to use his own graphics, sound files, 
						  video sequences and texts or resort to license-free graphics, audio, video clips and texts.<br />
						  All within the Internet offer namend and possibly protected brands and trademarks are subject to the provisions of applicable trademark law and the ownership 
						  rights of the registered owners. The mere mention does not imply that trademarks are not protected by law!<br />
						  The copyright for objects published by the author himself remains solely with the author of the homepage. Any reproduction or use of graphics, audio and 
						  video clips and texts in other electronic or printed publications is not permitted without the express permission of the author. <br />
						  <b>3. Privacy Policy</b><br />
						  If in the Internet offer the possibility to enter personal or business data (email addresses, names, addresses) is given, the input of these data results by 
						  the user on a voluntary basis. The use and payment of all services offered - if technically possible and reasonable - is also permitted without specification 
						  of any personal data or under specification of anonymized data or an alias. The use of the imprint or comparable published data like postal addresses, telephone 
						  or fax numbers and email addresses is not permitted to pass to third when not expressly requested. Legal action against senders of spam mails in violation of 
						  this prohibition are expressly reserved.<br /><br />
						  <b>4. Legal validity of this disclaimer</b><br />
						  This disclaimer is to be regarded as part of the internet publication which you were referred from this page. If sections or individual terms of this statement 
						  are not legal, no longer or not completely correspond, the remaining parts of the document in their content and validity are unaffected.
			</div>

	
</div>
