<style>
	#insertVocableUser{
		margin-left: 275px;
	}
	
	#answer_button{
		width: 75px;
		margin-left: 37px;
	}

	#goodjob{
		font-family: Impact, Charcoal, sans-serif;
		color: green;
	}
	
	#fail{
		font-family: Impact, Charcoal, sans-serif;
		color: red;
	}
</style>

<div class="content">
	
		<?php 
		$session = new Zend_Session_Namespace('game');
		?>

	
		<div id="blubb">
		<center>
		
	<table>	
		<thead>
			<tr>
			<th scope="col">Level</th>
			<th scope="col">#</th>
			<th scope="col">Fails</th>
			</tr>
		</thead>
			<tr>
				<td><?php echo $this->level?></td>
				<td><?php echo $this->questioncount?></td>
				<td><?php echo $this->fails?></td>
			</tr>				
	 	</table>
		
			<br>
			<?php echo $this->result?>
			<br>
			<?php echo $this->reward?>
			<?php echo $this->points?>
			<?php echo $this->reward2?>
			<br>
			<br>
			<form method="post" action='game'>
				<input type="submit" id="nextquestion" value="Next Question">
			</form>
					
		</center>
	</div>		
</div>