<style>
	#insertVocableUser{
		margin-left: 275px;
	}
	
	#answer_button{
		width: 75px;
		margin-left: 37px;
	}

</style>

<div class="content">
	
		<?php 
		$session = new Zend_Session_Namespace('game');
		
		?>

		<br>
		<div id="blubb">
		<center>
		
	<table>	
		<thead>
			<tr>
			<th scope="col">Level</th>
			<th scope="col">#</th>
			<th scope="col">Vocable</th>
			<th scope="col">Fails</th>
			</tr>
		</thead>
			<tr>
				<td><?php echo $this->level?></td>
				<td><?php echo $this->questioncount?></td>
				<td><?php echo $this->question[0][0]?></td>
				<td><?php echo $this->fails?></td>
			</tr>				
	 	</table>
		</center>
		</div>		
		
		<div id="insertVocableUser">
	<?php 
		$this->formQuesten->setAction('/game/checkanswer');
		echo $this->formQuesten;
	?>
		</div>
		
		<img src="/images/bavarian.gif" style="margin-left: 40px">
		
		<img src="/images/royalgard.png" style="margin-left: 360px">
	

	
</div>