<style>
	#gamestart_button-element{
		margin-left: 350px;
	}
	#gamestart_button{
		width: 75px;
	}
</style>

<div class="content">

	<?php
		$session= new Zend_Session_Namespace('loggedin');
		
		if ($session->loggedin == "91" or $session->loggedin == "92"){

			?>
			<div class="not_logged_in">
				<h1>Game</h1>
				<center>Hello <?php echo $this->user?>, press the startbutton to play the game!</center>
			</div>
			
			<br>
			<div id="gamestartButton">
			<?php 
			
				$this->formGameStart->setAction('game/game');
				echo $this->formGameStart;
			?>
			</div>
			<br>
		
			<?php }
		else{?>
			<div id="guest">
				<h1>Login to play the game!</h1>
			</div>
		<?php }?>

	
</div>
