<style>
	#insertVocableUser{
		margin-left: 275px;
	}
	
	#answer_button{
		width: 75px;
		margin-left: 37px;
	}
</style>

<div class="content">
	
		<?php 
		$session = new Zend_Session_Namespace('game');
		?>

	
		<div id="blubb">
		<center>
		
		<?php
		/* 
			var_dump($this->question);
			echo $this->question;
			echo $this->answer;
		*/
			?>
		
		<?php
		if ($this->question != NULL){
			foreach ($this->question as $vocable) {
			print <<<EOT
			{$vocable[0]}	
EOT;
			}			
		}
	 	?>
		</center>
		</div>		
		
		<div id="insertVocableUser">
	<?php 
		$this->formQuesten->setAction($this->url());
		echo $this->formQuesten;
	?>
		</div>	
		
		

	
</div>