


<div class="id="view-content">

	<h1>Registration</h1>

	<div id="register">
		<?php 
			$this->registerForm->setAction($this->url());
			echo $this->registerForm;
			
			if($this->success == 1){
				echo "Registration successful";
				}
			else if($this->success == -1){
				echo "False Password";
				}
			else if($this->regfehlgeschlagen != null){
				echo $this->regfehlgeschlagen;
			}
		?>
	</div>

</div>