
		
		<div class="imgleft" style="float: left; width: 350px; text-align: right; height: 100;"> 
			<a href="/">
			<img src="/images/dictro5.gif">
			</a>
		</div>

		
		<div class="imgright" style="float: right; width: 250px; height: 150px;">
			
			<div style="float:right; padding-right: 5px; height: 28px;">
			
			<a href="javascript:window.sidebar.addPanel('Dictro Translator/Uebersetzer', 'http://www.dictro.de', '');">Bookmark</a>
			
			<br>
			
			

			
		</div>

		<br><br><br><br><br>
		
			
				<?php
					$session = new Zend_Session_Namespace('loggedin');


					if ($session->loggedin == 91 or $session->loggedin == 92){
				?>
					<div class="logout" style="float:right; height: 28px; padding-right: 5px">
					<a href="/header/logout">Logout</a>
					</div>
				<?php
					}
					else{
				?>
					<div class="registration" style="float:right;height:28px;padding-right:5px"> 
					<a href="/registration">Sign In</a>
					</div>
				<?php
				}				
				?>
				
			
		
