<html>
	<head>
	<style>
		
	</style>
	</head>
	<body>
	
	
		<!--  <div class="imgleft" style="float: left; width: 350px; height: 100;"> 
			<img src="/images/pic1.jpg" alt="eine grafik">
			
		</div>
		
		<div class="imgmiddle" style="float: left; width: 250px; height: 100px;">
		<img src="/images/dictro.jpg" alt="eine grafik">
		</div>
		-->
		<div class="imgright" style="float: right; width: 250px; text-align: right; height: 150px;">
			<a href="/home.php">German</a>
			<a href="/home.php">English</a>
		</div>
	
	<br>
	<br>
	</body>
</html>
</div>