

<div class="content">
	
	<div id="container">
		
		<div class="contact"  style="float:right; height:500px; width: 750px">
			
			<center><h1>Kontakt</h1></center>
			<br>
			<div id="blubb">
			
				<form action="email.php" method="POST">
					
						<div class="form" style="float:right; width:600px">
							<dl>
								<dt>Name:</dt>
								<dd><input type="text" name="Versender" /></dd>
								<dt>E-Mail:</dt>
								<dd><input type="text" name="E-Mail" /></dd>
								<dt>Betreff:</dt>
								<dd><input type="text" name="Betreff" /></dd>
								<dt>Bemerkungen:</dt>
								<dd><textarea name="Bemerkungen" rows="10" cols="50"></textarea></dd>
							</dl>
							
							<div class="send" style="float:right; width:330px">
							<input type="submit" value="Senden" />
							<input type="reset" value="Zurücksetzen" />
							</div>
						</div>
			
				</form>
							
			</div>	
		</div>	
	</div>
</div>
