

<div class="content">
	
	<div id="container">
		
		<div class="contact"  style="float:right; height:500px; width: 750px">
			
			<center><h1>Contact</h1></center>
			<br>
			<div id="contact">
			
				<form action="email.php" method="POST">
					
						<div class="form" style="float:right; width:600px">
							<dl>
								<dt>Name:</dt>
								<dd><input type="text" name="Versender" /></dd>
								<dt>E-Mail:</dt>
								<dd><input type="text" name="E-Mail" /></dd>
								<dt>Subject:</dt>
								<dd><input type="text" name="Betreff" /></dd>
								<dt>Comment:</dt>
								<dd><textarea name="Bemerkungen" rows="10" cols="50"></textarea></dd>
							</dl>
							
							<div class="send" style="float:right; width:330px">
								
								<form method="get" action="/Contact/sendForm">
									<input type="submit" value="Send">
								</form>
								
							
								<form method="get" action="Contact/resetTextfield">
									<input type="submit" value="Reset">
								</form> 
								
							</div>
						</div>
			
				</form>
							
			</div>	
		</div>	
	</div>
</div>
