

<div class="content">
	
	<div id="container">
		
		<div class="contact"  style="float:left; height:500px; width: 807px">
			
			<center><h1>Contact</h1></center>
			
			<div id="contact">
			
				<form action="email.php" method="POST">
					
						<div class="form" style="float:right; width:650px">
							<dl>
								<dt>Name:</dt>
								<dd><input type="text" name="Versender" /></dd>
								<dt>E-Mail:</dt>
								<dd><input type="text" name="E-Mail" /></dd>
								<dt>Subject:</dt>
								<dd><input type="text" name="Betreff" /></dd>
								<dt>Comment:</dt>
								<dd><textarea name="Bemerkungen" rows="10" cols="50"></textarea></dd>
							</dl>
							
							<div class="send" style="float:right; width:330px">
							<input type="submit" value="Send" style="width: 70px">
							<input type="reset" value="Reset" style="width: 70px">
							</div>
						</div>
			
				</form>
							
			</div>	
		</div>	
	</div>
</div>
