<style>
	#index{
		margin-left: 37px;
	}
</style>


<div id="view-content">

	<h1>Translation</h1>
	
	
	
	<div class="flagg">
				
		<div id="gb" class="gb_ger" style="float:left; text-align: right; width: 320px; margin-top: 40px;">
			<img src="/images/ger_gb.bmp">
		</div>
		
		<div id="de" class="ger_gb" style="float:right; text-align: left; width: 315px; margin-top: 40px;">
			<img src="/images/gb_ger.bmp">
		</div>
					
	</div>
				
	<br>
	
	
	
			
	<div id="inhalt">
	
	<div style="padding-left: 273px">
	<?php
		$this->form->setAction($this->url());
		echo $this->form;
	?>
	</div>
		<center>
		<?php
		if ($this->translation != NULL){
		?>
			<table>
			<thead>
			<tr>
			<th scope="col">German</th>
			<th scope="col">English</th>
			</tr>
			</thead>
		<?php
			foreach ($this->translation as $vocable) {
			print <<<EOT
			<tr>
			<td>{$vocable[0]}</td>
			<td>{$vocable[1]}</td>
			</tr>		
EOT;
			}			
		}
	 	?>
		</table>
		
		</center>
	</div>
	

	
</div>