	<style>
	#footerwrap {
		visibility: hidden;
	}
	</style>
	
	
<div id="view-content">

	<h1>Translation</h1>
	
	<center>
	
	<div class="flagg">
				
		<div id="gb" class="gb_ger" style="float:left; text-align: right; width: 350px;">
			<img src="/images/gb_ger.bmp">
		</div>
		
		<div id="de" class="ger_gb" style="float:right; text-align: left; width: 350px;">
			<img src="/images/ger_gb.bmp">
		</div>
					
	</div>
				
	<div id="inhalt" style="min-height:392px;">
	<?php
		$this->form->setAction($this->url());
		echo $this->form;
	?>
	

		<?php
		if ($this->translation != NULL){
		?>
			<table>
			<thead>
			<tr>
			<th scope="col">German</th>
			<th scope="col">English</th>
			</tr>
			</thead>
		<?php
			foreach ($this->translation as $vocable) {
			print <<<EOT
			<tr>
			<td>{$vocable[0]}</td>
			<td>{$vocable[1]}</td>
			</tr>		
EOT;
			}			
		}
	 	?>
		</table>
		</center>

	</div>
	
		<div id="footerwrap2" >
	        <div id="footer2" style="float:right; width:800px">
	            <?php echo $this->action('index', 'footer'); ?>
	        </div>
        </div>
	
</div>