

	
	
	<div class="content"> 
	
		<div class="flagg"  style="padding: 20px">
			<div class="gb_ger" style="float:left; text-align: right; width: 350px;"">
				<img src="/images/gb_ger.bmp">
			</div>
			<div class="ger_gb" style="float:right; text-align: left; width: 350px;">
			<img src="/images/ger_gb.bmp">
			</div>
		</div>

		<div class="translate" style="float: left; width: 767px; height: 25; padding: 20px">
 				<center>
 				<form method="get" action="/Index/translate"> 
 					<input type="text" name="search">  
 					<input type="submit" value="translate"> 
 				</form> 
 				</center> 
 		</div> 
	</div> 

	
<div id="view-content">	
	<br><br>
	Hallo. Nein ich bin nicht die Home-Seite. Ich putze hier nur.
</div>			
	
		
	
<!-- 			/* -->
<!-- 			echo "<table>\n"; -->
<!-- 			while(($obj = mysql_fetch_object($res)) != NULL){ -->
<!-- 			echo "<tr><td>$obj->A</td>"; -->
<!-- 			if (($obj = mysql_fetch_object($res)) != NULL){ -->
<!-- 			echo "<td>$obj->B</td></tr>\n"; -->
<!-- 			} -->
<!-- 			else{ -->
<!-- 			echo "<td>&nbsp</td></tr>\n"; -->
<!-- 			} -->
<!-- 			} -->
<!-- 			"</table>\n"; -->
<!-- 			*/ -->
