
<!--	<div class="content"> -->
<!--		<div class="translate" style="float: left; width: 767px; height: 25; padding: 20px">
<!-- 				<form method="get" action="/Index/translate"> -->
<!-- 					<input type="text" name="search">  -->
<!-- 					<input type="submit" value="translate"> -->
<!-- 				</form>  -->
<!-- 		</div> -->
<!--		</div> -->
<!--	</div> -->
<div id="view-content">	
	Hallo. Nein ich bin nicht die Home-Seite. Ich putze hier nur.
</div>			
	
		
	
<!-- 			/* -->
<!-- 			echo "<table>\n"; -->
<!-- 			while(($obj = mysql_fetch_object($res)) != NULL){ -->
<!-- 			echo "<tr><td>$obj->A</td>"; -->
<!-- 			if (($obj = mysql_fetch_object($res)) != NULL){ -->
<!-- 			echo "<td>$obj->B</td></tr>\n"; -->
<!-- 			} -->
<!-- 			else{ -->
<!-- 			echo "<td>&nbsp</td></tr>\n"; -->
<!-- 			} -->
<!-- 			} -->
<!-- 			"</table>\n"; -->
<!-- 			*/ -->
