

<div class="content">

	<div class="table" style="float:left; height:500px; width: 807px">
			
		<h1>Highscore</h1>
			<br>
			<center>
			
		<?php
		if ($this->highscore != NULL){
		?>
			<table>
			<thead>
			<tr>
			<th scope="col">User</th>
			<th scope="col">Score</th>
			</tr>
			</thead>
		<?php
			foreach ($this->highscore as $highscore) {
			print <<<EOT
			<tr>
			<td>{$highscore[0]}</td>
			<td>{$highscore[1]}</td>
			</tr>		
EOT;
			}			
		}
	 	?>
	 	</table>
			</center>
			
	</div>
	
</div>
