	
	
	<style>
		P.blocktext {
		    margin-left: auto;
		    margin-right: auto;
		    width: 6em
		}
	</style>
	
	<?php
	$absatz = "<br><br><br><br><br><br><br>";
	?> 

	<div class="content" style="height:500px; width: 767px; padding: 20px">
		
		<?php echo $absatz?>
		<center>
			<div class="highscore" style="margin: auto auto">
					Highscore: $user_highscore
			<br><br>
					<input type="submit" value="Reset Highscore" style="width: 120px;">
			</div>
				
			<?php echo $absatz?>
			
			<div class="delt_user" style="">
				<input type="submit" value="Delete Account" style="width: 120px;">
			</div>
		</center>
		
	</div>
