

	<div class="content" style="height:500px; width: 767px; padding: 20px">
		
		<h1>Userfunctions</h1>
		
		<br><br><br><br><br>
		
		<center>
			<div class="highscore" style="margin: auto auto">
					Highscore: $user_highscore
			<br><br>
					<input type="submit" value="Reset Highscore" style="width: 120px;">
			</div>
				
			<br><br><br><br><br><br><br>
			
			<div class="delt_user" style="">
				<input type="submit" value="Delete Account" style="width: 120px;">
			</div>
		</center>
		
	</div>
