
<div class="menue">
	
	<div id="loginform" style="color: #fff; display: block; padding-left: 15px"> 
	
			<?php 
				$session = new Zend_Session_Namespace('loggedin');

				if ($session->loggedin != "91" && $session->loggedin != "92"){


					$this->loginForm->setAction($this->url());
					echo $this->loginForm;

				}
				

			?>

	</div>

		<div id="menu8" style="padding-left:15px">
		<br>
		<ul>
		   	<li><a href="/index"><span>Home</span></a></li>
		   	<li><a href="/game"><span>Game</span></a></li>
		   	<li><a href="/highscore"><span>Highscore</span></a></li>
		   	<li><a href="/contact"><span>Contact</span></a></li>
		   	<li><a href="/imprint"><span>Imprint</span></a></li>
		   	
		   	<br>
		   	
		   	<?php 
		   	if(($session->loggedin) == "91") {
			?>
				
				<span style="color: #fff;">Admin Area</span>
				<ul>
					<li><a href="/admin/insertvocable"><span>Insert</span></a></li>
					<li><a href="/admin/updatevocable"><span>Update</span></a></li>
					<li><a href="/admin/deletevocable"><span>Delete</span></a></li>
				</ul>
			<?php } 
			else if(($session->loggedin) == "92") {
			?>
		   		<li><a href="/user"><span>User</span></a></li>

		   	<?php } ?>

		</ul>
		</div>
		
</div>
