<head>
	<style>
		
	</style>
</head>



<body>
	
	
		<div style="margin-left: 0"> 
		<p>  Username <br/> <input type="text" name = "name" /></p>
		
		<p>  Password <br/> <input type="text" name = "passwd"/></p>

		<p><input style="margin-left: 90" type="submit" value = "Login" /></p>
		</div>
		
		<br>
		
		<div>
		 <ul style="margin-left: 0">
			<li><a href="../../../../../">Home</a></li>
		 
			<li><a href="/game">Game</a></li>
		
			<li><a href="/highscore">Highscore</a></li>
		
			<li><a href="/contact">Contact</a></li>
			
			<li><a href="/impressum">Imprint<br/><br/><br/></a></li>
			
			<li><a href="../../../../../application/views/scripts/admin/index.phtml">Adminfunctions</a></li>
			<li><a href="../../../../../application/views/scripts/user/index.phtml">Userfunctions</a></li>

			
		 </ul>
		</div>
	
	
</body>