<style>
	#footerwrap {
		visibility: hidden;
	}
</style>
	
<div class="content">
	
	<div id="inhalt" style="min-height:460px;">

	
		
		<?php
			$this->formSearch->setAction($this->url());
			echo $this->formSearch;
		?>
			<?php
			$this->formDelete->setAction($this->url());
			echo $this->formDelete;
			
			if ($this->deleteerfolgreich != null){
				echo $this->deleteerfolgreich;
			}
		?>

	
		<br><br><br>
	
		<?php
		if ($this->admin != NULL){
		?>
			<div class="table" style="float:left; width: 767px">
			<table>
			<thead>
			<tr>
			<th scope="col">VocID</th>
			<th scope="col">German</th>
			<th scope="col">English</th>
			</tr>
			</thead>
		<?php
			foreach ($this->admin as $vocable) {
			print <<<EOT
			<tr>
			<td>{$vocable[0]}</td>
			<td>{$vocable[1]}</td>
			<td>{$vocable[2]}</td>
			</tr>		
EOT;
			}
		}
		?>
		</table>
		</div>
		
		
	</div>
		
		
	<div id="footerwrap2" >
        <div id="footer2">
            <?php echo $this->action('index', 'footer'); ?>
	        </div>
    </div>
        
</div>
