
<div class="content" style="height:500px; width: 767px; padding: 20px">
	
	<div class="search_textfield" style="float: left; width: 450px; height: 50;">
	<form method="get" action="search_admin.php">
		<input type="text" name="search_admin">
		<input type="submit" value="search" style="width: 80px;">
	</form> 
	</div>

	<div class="searchbuttonright" style="float: right; width: 250px; text-align: right; height: 50px;">
		<input type="submit" value="Delete" style="width: 80px;">
		<input type="submit" value="Update" style="width: 80px;">
	</div>

	<br><br><br>

	<div class="table" style="float:left; width: 767px">
		<table border=1>
			<tr>
			<th width="350">German</th>
			<th width="350">English</th>
			<th width="75">Level</th>
			</tr>
			<tr>
			<td width="350">test</td>
			<td width="350">test</td>
			<td width="75">test</td>
			</tr>
		</table>
	</div>
	
	<br><br><br><br><br>

	<div class="insert">
		<form method="get" action="search_admin.php">
			<input type="text" name="german_voc" style="width: 340px">
			<input type="text" name="english_voc" style="width: 340px">
			<input type="text" name="level_voc" style="width: 75px">
			<br><br>
			
			<input type="submit" value="Insert" style="float:right; width: 80px;">
		</form>
	</div>

	
</div>

