<style>
	#footerwrap {
		visibility: hidden;
	}
</style>
	
<div class="content">
	
	<div id="inhalt" style="min-height:460px;">
		
		<div class="search_textfield" style="float: left; width: 450px; height: 50;">
		<form method="get" action="search_admin.php">
			<input type="text" name="search_admin">
			<input type="submit" value="Search" style="width: 80px;">
		</form> 
		</div>
	
	
	
		<br><br><br>
	
		<div class="table" style="float:left; width: 767px">
			<table>
				<tr>
				<th width="350">German</th>
				<th width="350">English</th>
				<th width="75"><center>Level<center></th>
				</tr>
				<tr>
				<td width="350">Viech</td>
				<td width="350">Jax</td>
				<td width="75"><center>5<center></td>
				</tr>
			</table>
		</div>
		
		<br><br><br><br><br>
	
		<div class="insert">
			<form method="get" action="search_admin.php">
				<input type="text" name="german_voc" style="width: 340px">
				<input type="text" name="english_voc" style="width: 340px">
				<input type="text" name="level_voc" style="width: 75px">
				<br><br>
				
			<div id="buttons">
				<input type="submit" id="adminButtons" value="Insert">
				<input type="submit" id="adminButtons" value="Update">
				<input type="submit" id="adminButtons" value="Delete">
			</div>
				
				
			</form>
		</div>
	
	</div>
	
	<div id="footerwrap2" >
        <div id="footer2">
            <?php echo $this->action('index', 'footer'); ?>
	        </div>
    </div>
        
</div>

