
	
<div class="content">
	
	<div id="admin">

		<?php
			$this->formSearch->setAction($this->url());
			echo $this->formSearch;
		?>
			<?php
			$this->formInsert->setAction($this->url());
			echo $this->formInsert;
			
			if ($this->inserterfolgreich != null){
				echo $this->inserterfolgreich;
			}
		?>

	
		<br>
		<center>
		<?php
		if ($this->admin != NULL){
		?>
			<table>
			<thead>
			<tr>
			<th scope="col">German</th>
			<th scope="col">English</th>
			</tr>
			</thead>
		<?php
			foreach ($this->admin as $vocable) {
			print <<<EOT
			<tr>
			<td>{$vocable[0]}</td>
			<td>{$vocable[1]}</td>
			</tr>		
EOT;
			}
		}
		?>
			</table>
			</center>
	</div>

</div>
