
<div id="view-content">
	
	<div id="inhalt">
		
		<?php
			$this->formSearch->setAction($this->url());
			echo $this->formSearch;
		?>
		<?php
			$this->formUpdate->setAction($this->url());
			echo $this->formUpdate;
			
			
			
		?>

		<br>
		<center>
		<?php
		if ($this->admin != NULL){
		?>
			<table>
			<thead>
			<tr>
			<th scope="col">ID</th>
			<th scope="col">German</th>
			<th scope="col">English</th>
			<th scope="col">Level</th>
			</tr>
			</thead>
		<?php
			foreach ($this->admin as $vocable) {
			print <<<EOT
			<tr>
			<td>{$vocable[0]}</td>
			<td>{$vocable[1]}</td>
			<td>{$vocable[2]}</td>
			<td>{$vocable[3]}</td>
			</tr>		
EOT;
			}
		}
		?>
		</table>
		</center>
 
	</div>

</div>